# Add `~/bin` to the `$PATH`
export PATH="$HOME/bin:$PATH";

DOTFILES=$HOME/.dotfiles

# source file
source_if_exists () {
    if test -r "$1"; then
        source "$1"
    fi
}

# source from folder
source_files(){
  local folder=$1
  find "$folder" -type f | while read -r file; do
    source_if_exists "$file"
  done
}

# Load the dotfiles
source_files $DOTFILES

# oh my zsh configuration

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh